package id.ac.ui.cs.advprog.eshop.repository;

import id.ac.ui.cs.advprog.eshop.model.Product;
import org.springframework.stereotype.Repository;

import java.util.*;

@Repository
public class ProductRepository {
    private List<Product> productData = new ArrayList<>();
    private int productId = 1;

    //ID is generated by the repository to ease the edit and delete process
    //it was not specified in the module, but it is assumed that the ID is unique
    public Product create(Product product){
        product.setProductId(String.valueOf(productId++)); //ID is generated by the repository
        productData.add(product);
        return product;
    }

    public Product deleteById(String productId){
        Iterator<Product> productIterator = productData.iterator();
        while(productIterator.hasNext()){
            Product product = productIterator.next();
            if(product.getProductId().equals(productId)){
                productIterator.remove();
                return product;
            }
        }
        return null;
    }

    public Iterator<Product> findAll(){
        return productData.iterator();
    }
}