package id.ac.ui.cs.advprog.eshop.repository;

import id.ac.ui.cs.advprog.eshop.model.Product;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.UUID;
@Repository
public class ProductRepository {
    private List<Product> productData = new ArrayList<>();


    //ID is generated by the repository to ease the edit and delete process
    //it was not specified in the module, but it is assumed that the ID is unique
    public Product create(Product product){
        product.setProductId(UUID.randomUUID().toString()); //V4 UUID as unique ID
        productData.add(product);
        return product;
    }

    public Iterator<Product> findAll(){
        return productData.iterator();
    }
}

